### ISSUE TITLE
crash during load test

### ISSUE THREAD

**Issue by MayamaTakeshi** [MayamaTakeshi/mrcp_server#15]
<Buffer d3 df 2f 1e 1e 42 9e 91 96 b9 1d 12 19 3b a9 a1 ae da eb b6 ab bd 2b 17 17 2d a2 91 93 ab 27 18 1c 37 bd b8 eb 4e bf a3 9d ab 2d 14 12 22 ac 94 94 a7 ... 110 more bytes>                                 
rtp_session data
<Buffer d3 df 2f 1e 1e 42 9e 91 96 b9 1d 12 19 3b a9 a1 ae da eb b6 ab bd 2b 17 17 2d a2 91 93 ab 27 18 1c 37 bd b8 eb 4e bf a3 9d ab 2d 14 12 22 ac 94 94 a7 ... 110 more bytes>                                 
2021-02-11 17:13:47.170 info: speechsynther.js got TERMINATE
2021-02-11 17:13:47.170 info: speechrecoger.js got RECOGNITION_COMPLETED
2021-02-11 17:13:47.170 info: speechrecoger.js sending event RECOGNITION-COMPLETE 0123456789ABC}
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:457:14)
    at MrcpSocket._write (/mnt/ssd/work/src/git/MayamaTakeshi/mrcp_server/node_modules/mrcp/src/mrcp_socket.js:152:18)                                                                                            
    at doWrite (_stream_writable.js:403:12)
    at writeOrBuffer (_stream_writable.js:387:5)
    at MrcpSocket.Writable.write (_stream_writable.js:318:11)
    at Object.safe_write (/mnt/ssd/work/src/git/MayamaTakeshi/mrcp_server/src/utils.js:103:9)
    at send_recognition_complete (/mnt/ssd/work/src/git/MayamaTakeshi/mrcp_server/src/actors/speechrecoger.js:32:4)                                                                                               
    at Object.<anonymous> (/mnt/ssd/work/src/git/MayamaTakeshi/mrcp_server/src/actors/speechrecoger.js:101:4)                                                                                                     
    at Immediate.<anonymous> (/mnt/ssd/work/src/git/MayamaTakeshi/mrcp_server/node_modules/nact/lib/actor.js:207:49)                                                                                              
    at processImmediate (internal/timers.js:461:21)
Emitted 'error' event on MrcpSocket instance at:
    at Socket.<anonymous> (/mnt/ssd/work/src/git/MayamaTakeshi/mrcp_server/node_modules/mrcp/src/mrcp_socket.js:64:42)                                                                                            
    at Socket.emit (events.js:314:20)
    at emitErrorNT (net.js:1344:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
    at runNextTicks (internal/process/task_queues.js:66:3)
    at processImmediate (internal/timers.js:434:9) {
  code: 'EPIPE'
}
takeshi@takeshi-debian:~/work/src/git/MayamaTakeshi/mrcp_server$

**Comment by MayamaTakeshi** [comment]
It can be easily reproduced by killing the client (Ctrl-C) while MRCP request is ongoing. Ex:


takeshi@takeshi-debian:~/work/src/git/MayamaTakeshi/mrcp_client$ node speechsynth_client.js 127.0.0.1 8070 dtmf dtmf 12341234123412341234124213412341234123412341234
command accepted
^C


takeshi@takeshi-debian:~/work/src/git/MayamaTakeshi/mrcp_server$ 

2021-02-11 17:28:30.174 info: speechsynther.js got START
2021-02-11 17:28:30.183 info: Incoming request ACK
2021-02-11 17:28:30.186 info: speechsynther.js got MRCP_MESSAGE
2021-02-11 17:28:30.186 info: {"type":"request","version":"2.0","method":"SPEAK","request_id":1,"headers":{"channel-identifier":"5be8235e-fefd-44fe-a13d-29c7c68144cc@speechsynth","content-type":"text/plain","speech-language":"dtmf","voice-name":"dtmf","content-length":"47"},"body":"12341234123412341234124213412341234123412341234"}                                                                                         
2021-02-11 17:28:30.187 info: speechsynther.js sending reply 200 IN-PROGRESS
2021-02-11 17:28:30.188 info: dtmf_ss_agent.js got START


2021-02-11 17:28:36.993 info: speechsynther.js got MEDIA_OPERATION_COMPLETE
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:457:14)
    at MrcpSocket._write (/mnt/ssd/work/src/git/MayamaTakeshi/mrcp_server/node_modules/mrcp/src/mrcp_socket.js:152:18)                                                                                            
    at doWrite (_stream_writable.js:403:12)
    at writeOrBuffer (_stream_writable.js:387:5)
    at MrcpSocket.Writable.write (_stream_writable.js:318:11)
    at Object.safe_write (/mnt/ssd/work/src/git/MayamaTakeshi/mrcp_server/src/utils.js:103:9)
    at Object.<anonymous> (/mnt/ssd/work/src/git/MayamaTakeshi/mrcp_server/src/actors/speechsynther.js:61:6)                                                                                                      
    at Immediate.<anonymous> (/mnt/ssd/work/src/git/MayamaTakeshi/mrcp_server/node_modules/nact/lib/actor.js:207:49)                                                                                              
    at processImmediate (internal/timers.js:461:21)
Emitted 'error' event on MrcpSocket instance at:
    at Socket.<anonymous> (/mnt/ssd/work/src/git/MayamaTakeshi/mrcp_server/node_modules/mrcp/src/mrcp_socket.js:64:42)                                                                                            
    at Socket.emit (events.js:314:20)
    at emitErrorNT (net.js:1344:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
    at runNextTicks (internal/process/task_queues.js:66:3)
    at processImmediate (internal/timers.js:434:9) {
  code: 'EPIPE'
}
