### ISSUE TITLE
sip_server actor stopped receiving messages after some time during load test

### ISSUE THREAD

**Issue by MayamaTakeshi** [MayamaTakeshi/mrcp_server#25]
Commit 799333615d8fe074583ed477c7280f4b23fd7467

2021-02-13 19:53:06.166 info: affc095e-f6db-424b-a38a-93bef5572423 (sip_server.js:199) got SIP request INVITE                                                                                                     
2021-02-13 19:53:06.167 info: affc095e-f6db-424b-a38a-93bef5572423 (sip_server.js:67) got new call
2021-02-13 19:53:06.167 info: affc095e-f6db-424b-a38a-93bef5572423 (sip_server.js:119) allocated rtp_session 182                                                                                                  
2021-02-13 19:53:06.167 info: affc095e-f6db-424b-a38a-93bef5572423 (sip_server.js:135) added to registrar                                                                                                         
2021-02-13 19:53:06.167 info: affc095e-f6db-424b-a38a-93bef5572423 (sip_server.js:140) accepted with 100 Trying                                                                                                   
2021-02-13 19:53:06.167 info: mrcp_server (mrcp_server.js:27) got {"type":"SESSION_CREATED","sender":{"path":{"system":"nmf9r1-1ltm43c-14iac59-1ppxokp","parts":["sip_server"]},"name":"sip_server","parent":{"path":{"system":"nmf9r1-1ltm43c-14iac59-1ppxokp","parts":[]},"system":{"name":"nmf9r1-1ltm43c-14iac59-1ppxokp"},"name":"nmf9r1-1ltm43c-14iac59-1ppxokp","type":"system"},"system":{"name":"nmf9r1-1ltm43c-14iac59-1ppxokp"},"type":"actor"},"data":{"uuid":"affc095e-f6db-424b-a38a-93bef5572423","sip_req":{"method":"INVITE","uri":"sip:127.0.0.1:8070","version":"2.0","headers":{"to":{"uri":"sip:127.0.0.1:8070","params":{}},"from":{"uri":"sip:mrcp_client@192.168.0.109:5061","params":{"tag":"664389"}},"call-id":"affc095e-f6db-424b-a38a-93bef5572423","cseq":{"seq":95133,"method":"INVITE"},"content-type":"application/sdp","contact":[{"uri":"sip:mrcp_client@192.168.0.109:5061","params":{}}],"via":[{"version":"2.0","protocol":"UDP","host":"192.168.0.109","port":5061,"params":{"branch":"z9hG4bK261004","rport":5061,"received":"192.168.0.109"}}],"content-length":281},"content":"v=0\r\no=mrcp_client 5772550679930491611 4608916746797952899 IN IP4 192.168.0.109\r\ns=-\r\nc=IN IP4 192.168.0.109\r\nt=0 0\r\nm=application 9 TCP/MRCPv2 1\r\na=setup:active\r\na=connection:new\r\na=resource:speechsynth\r\na=cmid:1\r\nm=audio 10002 RTP/AVP 0\r\na=rtpmap:0 PCMU/8000\r\na=recvonly\r\na=mid:1"},"remote_rtp_ip":"192.168.0.109","resource":"speechsynth","connection":"new","remote_rtp_port":10002,"rtp_payloads":["0"],"local_ip":"127.0.0.1","local_port":10364,"rtp_session":{"_socket":{"_events":{"data":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]},"_eventsCount":3,"type":"udp4"},"id":182,"local_ip":"127.0.0.1","local_port":10364,"remote_ip":"192.168.0.109","remote_port":10002,"payload_type":0,"ssrc":2519799697,"seq_num":1,"time_stamp":160,"activity_ts":1613213586167,"_hdr":{"type":"Buffer","data":[128,0,0,0,0,0,0,1,150,49,23,145]}}}}                                                                                       
2021-02-13 19:53:06.168 error: affc095e-f6db-424b-a38a-93bef5572423 (mrcp_server.js:84) setting handler for speechsynth                                                                                           
2021-02-13 19:53:06.168 info: affc095e-f6db-424b-a38a-93bef5572423 (speechsynther.js:28) got START
2021-02-13 19:53:11.751 warn: affc095e-f6db-424b-a38a-93bef5572423 (sip_server.js:262) Terminating call due to RTP inactivity                                                                                     
2021-02-13 19:53:11.752 info: affc095e-f6db-424b-a38a-93bef5572423 (sip_server.js:264) deallocated rtp_session 182                                                                                                
2021-02-13 19:53:11.752 info: affc095e-f6db-424b-a38a-93bef5572423 (sip_server.js:271) removed from registrar                                                                                                     
2021-02-13 19:53:11.752 info: affc095e-f6db-424b-a38a-93bef5572423 (sip_server.js:291) refused with 480 Temporarily Unavailable                                                                                   
2021-02-13 19:53:11.752 info: mrcp_server (mrcp_server.js:27) got {"type":"SESSION_TERMINATED","uuid":"affc095e-f6db-424b-a38a-93bef5572423","handler":{"path":{"system":"nmf9r1-1ltm43c-14iac59-1ppxokp","parts":["mrcp_server","anonymous-551125823"]},"name":"anonymous-551125823","parent":{"path":{"system":"nmf9r1-1ltm43c-14iac59-1ppxokp","parts":["mrcp_server"]},"name":"mrcp_server","parent":{"path":{"system":"nmf9r1-1ltm43c-14iac59-1ppxokp","parts":[]},"system":{"name":"nmf9r1-1ltm43c-14iac59-1ppxokp"},"name":"nmf9r1-1ltm43c-14iac59-1ppxokp","type":"system"},"system":{"name":"nmf9r1-1ltm43c-14iac59-1ppxokp"},"type":"actor"},"system":{"name":"nmf9r1-1ltm43c-14iac59-1ppxokp"},"type":"actor"}}
2021-02-13 19:53:11.752 info: affc095e-f6db-424b-a38a-93bef5572423 (speechsynther.js:28) got TERMINATE

In the above we should see sip_server notifying reception of SESSION_CREATED_ACK.
This might be a problem with nack library.

**Comment by MayamaTakeshi** [comment]
Yes. It seems to be a problem with nact. 

For comparison I added logging of the nack object sip_server and it is the same:

OK:
2021-02-13 21:02:30.071 info: 9b4f7eac-0a00-4e51-9592-5ff9d98cb5c7 (mrcp_server.js:89) sending SESSION_CREATED_ACK to {"path":{"system":"1vn4udm-14tqimt-1eg3aqo-4idzwb","parts":["sip_server"]},"name":"sip_server","parent":{"path":{"system":"1vn4udm-14tqimt-1eg3aqo-4idzwb","parts":[]},"system":{"name":"1vn4udm-14tqimt-1eg3aqo-4idzwb"},"name":"1vn4udm-14tqimt-1eg3aqo-4idzwb","type":"system"},"system":{"name":"1vn4udm-14tqimt-1eg3aqo-4idzwb"},"type":"actor"}
2021-02-13 21:02:30.072 info: sip_server (sip_server.js:230) got SESSION_CREATED_ACK

NG:
2021-02-13 21:30:14.226 info: 4a47ee65-ecb7-46ce-9669-387b68906892 (mrcp_server.js:89) sending SESSION_CREATED_ACK to {"path":{"system":"1vn4udm-14tqimt-1eg3aqo-4idzwb","parts":
["sip_server"]},"name":"sip_server","parent":{"path":{"system":"1vn4udm-14tqimt-1eg3aqo-4idzwb","parts":[]},"system":{"name":"1vn4udm-14tqimt-1eg3aqo-4idzwb"},"name":"1vn4udm-14tqimt-1eg3aqo-4idzwb","type":"system"},"system":{"name":"1vn4udm-14tqimt-1eg3aqo-4idzwb"},"type":"actor"}
(no 'got SESSION_CREATED_ACK')

Note that sip_server is still alive:

2021-02-13 21:30:19.985 info: 4a47ee65-ecb7-46ce-9669-387b68906892 (sip_server.js:291) refused with 480 Temporarily Unavailable

and the nack id used by mrcp_server to send SESSION_CREATED_ACK to sip_server is the one that sip_server itself sent to it on the SESSION_CREATED message.

**Comment by MayamaTakeshi** [comment]
We could reproduce this and this time we have the error written after 'got SESSION_CREATED_ACK':

2021-02-13 21:29:21.580 info: sip_server (sip_server.js:230) got SESSION_CREATED_ACK
1vn4udm-14tqimt-1eg3aqo-4idzwb://sip_server: The following error was raised when processing message {
  type: 'SESSION_CREATED_ACK',
  data: { uuid: '87a3970b-f55a-4076-964d-c137f17d7792' }
}:
TypeError: Cannot read property 'rtp_session' of undefined
    at Object.<anonymous> (/mnt/ssd/work/src/git/MayamaTakeshi/mrcp_server/src/actors/sip_server.js:307:36)
    at Immediate._onImmediate (/mnt/ssd/work/src/git/MayamaTakeshi/mrcp_server/node_modules/nact/lib/actor.js:207:49)
    at processImmediate (internal/timers.js:461:21)
Terminating faulted actor

So the situation is: although the sip_server actor was terminated, it has callback functions that continue to be called. 
So it was sending message SESSION_CREATED passing the original ctx.self that it stored upon creation but actually this nact id is inactive as the actor is considered dead by nact.

**Comment by MayamaTakeshi** [comment]
Wrong code:
I was using:
  if(!uuid in registrar) 
when it should have been:
  if(!(uuid in registrar)) 
However, the above is inefficient as it traverses all the object inheritance chain.
So I changed it to
  if(!registrar.hasOwnProperty(uuid))
